//
//  WeatherModels.swift
//  OpenWeatherApp
//
//  Created by Paul Matar on 04/07/2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//
import Foundation

typealias WeatherViewModel = WeatherType.GeoWeather.ViewModel
typealias WeatherRequest = WeatherType.GeoWeather.Request
typealias WeatherResponse = WeatherType.GeoWeather.Response
typealias WeatherCell = WeatherType.GeoWeather.ViewModel.CellViewModel

enum WeatherType {
    
    enum GeoWeather {
        struct Request {
            let lat, lon: Double
        }
        
        struct Response {
            let weatherList: [List]
            let city: City?
            let error: Error?
        }
        
        struct ViewModel {
            struct CellViewModel {
                let labelText: String
                let description: String
                let image: String
            }
            
            let cells: [WeatherCell]
            let headerText: String?
            let error: String?
        }
    }
}

